### ISSUE TITLE
[feature] Put back into cache upon fired events on the models

### ISSUE THREAD

**Issue by davidstefando** [renoki-co/laravel-eloquent-query-cache#66]
Hi,
I was using this amazing package on my project.
I have requirement to modify cache content directly, in parralel with the update of database. So I could prevent re query everytime. So I need to get the key of a cache.

I'm using newest version and using redis as my cache driver

After making some debug into redis every key looks like prefixed with string like this
my_project_database_my_project_cache:015cd49cea3e5add0c86b2e6940d434f0e2b1353:leqc:theactualkey

I just want to ask, where is 015cd49cea3e5add0c86b2e6940d434f0e2b1353 come from?

**Comment by Magnie** [comment]
I ran into a similar issue with the above method where scopes (Soft Deletes) weren't being included in the query, and since the `Model::find()` method also adds `limit 1` to the query, this is how I was able to replicate the proper key:
```php
    public function getModelCacheKey(): string
    {
        $key = $this->newQueryWithoutRelationships()
            ->whereKey($this->getPrimaryKeyValue())
            ->applyScopes()
            ->take(1)
            ->getQuery()
            ->getCacheKey();
        return $key;
    }
```
Then I used this to cache an existing model:
```php
    public $cacheFor = 60 * 60 * 24; // Seconds * Minutes * Hours in a day
    public function cacheMe()
    {
        self::find($this->getKey());
    }
```
Although it requires a call to the DB (I have `'sticky' => true` in `config/database.php` to avoid race conditions with the readonly DB), it uses all the default caching behavior of the library. However, since the original question wants to avoid unnecessary DB calls, this can be overridden with:
```php
$tags = $this->getCacheBaseTags();
Cache::tags($tags)->put($this->getModelCacheKey(), $this);
```

This is the full trait I created:
```php
trait CustomCache
{
    use QueryCacheable;

    public $cacheFor = 60 * 60 * 24; // Seconds * Minutes * Hours in a day
    public $_retrievedFromCache = false; // Used for unit tests

    // We do NOT want automatic invalidation. We will handle that ourselves.
    protected static $flushCacheOnUpdate = false;

    public static function bootCustomCache()
    {
        self::observe(CacheObserver::class); // 
    }

    public function getModelCacheKey(): string
    {
        $key = $this->newQueryWithoutRelationships()
            ->whereKey($this->getKey())
            ->applyScopes()
            ->take(1)
            ->getQuery()
            ->getCacheKey();
        return $key;
    }

    public function cacheMe()
    {
        self::find($this->getKey());
    }
}
```
And then the observer in case anyone is curious:
```php
class CacheObserver
{
    public $afterCommit = true; // Only make calls after the DB transaction finishes

    public function saved($model)
    {
        $model->cacheMe();
    }

    public function retrieved($model)
    {
        $model->_retrievedFromCache = true;
    }
}
```
Working on a `deleted()` event for clearing only a single cached model, but that is a little more complicated and this post is long enough as is.
